export const PLANET_CHARS = [
  {
    name: "Bittu",
    role: "IIT Intern",
    emoji: "🎓",
    band: "80Hz",
    color: "#FF6464",
    slackStatuses: [
      "grinding 🔥",
      "leetcoding (not on company time)",
      "leetcoding (definitely on company time)",
      "away: bathroom (still grinding)",
      "optimising algo O(n log n) → O(log n) 💪",
    ],
    shrinkReply: "sir noted. (will not action.)",
    dragReplies: [
      "Bittu changed status to: grinding 🔥",
      "Bittu is now: leetcoding vigorously",
      "Bittu updated status: debugging production (it was a semicolon)",
    ],
  },
  {
    name: "Pinky Ma'am",
    role: "Senior Manager, Low-Mids",
    emoji: "📞",
    band: "250Hz",
    color: "#FFC15B",
    slackStatuses: [
      "in a meeting 📞",
      "in a meeting (different meeting)",
      "stepping out (7-hr meeting)",
      "be right back (still on a call)",
      "blocked: calendar full till 2027",
    ],
    shrinkReply: "currently in a meeting. please circle back. 🔄",
    dragReplies: [
      "Pinky Ma'am changed status to: in a meeting 📞",
      "Pinky Ma'am is: stepping out for a quick sync",
      "Pinky Ma'am updated status: blocked (calendar full)",
    ],
  },
  {
    name: "Rahul",
    role: "Lead Engineer (Burnout: 94%)",
    emoji: "😮‍💨",
    band: "800Hz",
    color: "#7CFFB2",
    slackStatuses: [
      "kya batayein bhai 😮‍💨",
      "exists 🌫️",
      "technically present",
      "kya batayein 😶",
      "mai hoon kya? 🤷",
    ],
    shrinkReply: "kya batayein bhai. noted. (sigh)",
    dragReplies: [
      "Rahul changed status to: kya batayein bhai 😮‍💨",
      "Rahul is: doing the needful",
      "Rahul updated status: surviving",
    ],
  },
  {
    name: "Aryan",
    role: "Strategy (ex-McKinsey)",
    emoji: "✈️",
    band: "2.5kHz",
    color: "#5CE5FF",
    slackStatuses: [
      "building in public 🚀",
      "writing Substack post",
      "Q4 framework alignment",
      "synergising 📊",
      "offline: deep work sprint",
    ],
    shrinkReply: "looping in the stakeholders. action item raised.",
    dragReplies: [
      "Aryan changed status to: building in public 🚀",
      "Aryan is: Q4 framework alignment",
      "Aryan updated status: synergising across verticals",
    ],
  },
  {
    name: "Saxena Sir",
    role: "Founder (Retired In Place)",
    emoji: "🪷",
    band: "8kHz",
    color: "#C57CFF",
    slackStatuses: [
      "🙏",
      ".",
      "theek hai.",
      "🕯️",
      "",
    ],
    shrinkReply: "theek hai.",
    dragReplies: [
      "Saxena Sir changed status to: 🙏",
      "Saxena Sir is: present (spiritually)",
      "Saxena Sir: theek hai.",
    ],
  },
] as const;

export type PlanetIndex = 0 | 1 | 2 | 3 | 4;
